export const data = [
  {
    title: 'Catering 1',
    description: 'Italian • Delivery',
    link: 'https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app',
    image: 'https://source.unsplash.com/600x400/?catering',
  },
  {
    title: 'Catering 2',
    description: 'Mexican • Catering',
    link: 'https://nextjs.org/learn?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app',
    image: 'https://source.unsplash.com/600x400/?mexico',
  },
  {
    title: 'Catering 3',
    description: 'Italian • Delivery',
    link: 'https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app',
    image: 'https://source.unsplash.com/600x400/?italian-food',
  },
  {
    title: 'Catering 4',
    description: 'Italian • Delivery',
    link: 'https://vercel.com/new?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app',
    image: 'https://source.unsplash.com/600x400/?food',
  },
  {
    title: 'Catering 2',
    description: 'Italian • Delivery',
    link: 'https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app',
    image: 'https://source.unsplash.com/600x400/?pasta',
  },
  {
    title: 'Catering 3',
    description: 'Italian • Delivery',
    link: 'https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app',
    image: 'https://source.unsplash.com/600x400/?cheese',
  },
  {
    title: 'Catering 4',
    description: 'Italian • Delivery',
    link: 'https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app',
    image: 'https://source.unsplash.com/600x400/?wedding',
  },
  {
    title: 'Catering 5',
    description: 'Latin American • Delivery',
    link: 'https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app',
    image: 'https://source.unsplash.com/600x400/?meal',
  },
  {
    title: 'Catering 6',
    description: 'Japanese • Delivery',
    link: 'https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app',
    image: 'https://source.unsplash.com/600x400/?dinner',
  },
  {
    title: 'Catering 7',
    description: 'Italian • Delivery',
    link: 'https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app',
    image: 'https://source.unsplash.com/600x400/?lunch',
  },
  {
    title: 'Catering 8',
    description: 'Mexican • Delivery',
    link: 'https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app',
    image: 'https://source.unsplash.com/600x400/?breakfast',
  },
  {
    title: 'Catering 9',
    description: 'Christmas • Delivery',
    link: 'https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app',
    image: 'https://source.unsplash.com/600x400/?eating',
  },
  {
    title: 'Catering 10',
    description: 'Italian • Catering',
    link: 'https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app',
    image: 'https://source.unsplash.com/600x400/?delicious',
  },
  {
    title: 'Catering 11',
    description: 'Italian • Delivery',
    link: 'https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app',
    image: 'https://source.unsplash.com/600x400/?fast-food',
  },
];
